clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'clients'

urlpatterns = [
    # clients
    url(r'^$', views.ClientListView.as_view(), name='client_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.ClientDetailView.as_view(), name='client_detail'),
    url(r'^add/$', views.CreateClient.as_view(), name='client-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateClient.as_view(), name='client-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteClient.as_view(), name='client-delete'),

    # client contacts
    url(r'^(?P<pk>[0-9]+)/contacts/$', views.ClientContactListView.as_view(), name='contact_list'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/$', views.ClientContactDetailView.as_view(), name='contact_detail'),
    url(r'^client_contacts/add/$', views.CreateClientContact.as_view(), name='contact-add'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/update/$', views.UpdateClientContact.as_view(), name='contact-update'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/delete/$', views.DeleteClientContact.as_view(), name='contact-delete'),


]

sellers/urls.py
from django.conf.urls import url
from . import views

app_name = 'sellers'

urlpatterns = [
    #sellers
    url(r'^$', views.SellerListView.as_view(), name="seller_list"),
    url(r'^add/$', views.CreateSeller.as_view(), name="seller-add"),
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateSeller.as_view(), name='seller-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteSeller.as_view(), name='seller-delete'),

]

smartERP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'clients/', include('clients.urls', namespace='clients')),
    url(r'sellers/', include('sellers.urls', namespace='sellers')),
    url(r'management/', include('management.urls', namespace='management')),
    url(r'payment/', include('payment.urls', namespace='payment')),
    url(r'inventory/', include('inventory.urls', namespace='inventory')),
]

sellers/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Seller(models.Model):
    seller_code = models.CharField(max_length=10, verbose_name="Codigo Vendedor", unique="True")
    seller_name = models.CharField(max_length=50, verbose_name="Nombre Vendedor")
    seller_address = models.CharField(max_length=100, blank=True, verbose_name="Direccion")
    seller_comuna = models.CharField(max_length=50, blank=True, verbose_name="Comuna")
    seller_ciudad = models.CharField(max_length=50, blank=True, verbose_name="Ciudad")
    seller_region = models.CharField(max_length=50, blank=True, verbose_name="Region")
    seller_tel = models.CharField(max_length=50, blank=True, verbose_name="Telefono")
    seller_email = models.EmailField(blank=True, verbose_name="Email")
    is_active = models.BooleanField(default=True, verbose_name="Activo")

    def get_absolute_url(self):
        return reverse("sellers:seller_list")

    def __str__(self):
        return self.seller_code + ' - ' + self.seller_name

    class Meta:
        ordering = ['seller_code']

sellers/forms.py
from django import forms
from .models import Seller


class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = '__all__'
        widgets = {
            'seller_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'seller_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'seller_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'seller_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'seller_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'seller_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'seller_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'seller_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


class SellerUpdateForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = '__all__'
        widgets = {
            'seller_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'seller_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'seller_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'seller_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'seller_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'seller_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'seller_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'seller_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }

sellers/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Seller
from .forms import SellerForm, SellerUpdateForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.html import mark_safe
from django.db.models.deletion import ProtectedError


# Create your views here.
class SellerListView(ListView):
    template_name = 'sellers/seller_list.html'

    def get_queryset(self):
        return Seller.objects.all()


class CreateSeller(SuccessMessageMixin, CreateView):
    model = Seller
    form_class = SellerForm
    template_name_suffix = '_create_form'
    success_message = "El vendedor ha sido creado con exito"


class UpdateSeller(UpdateView):
    model = Seller
    form_class = SellerUpdateForm
    template_name_suffix = '_update_form'


class DeleteSeller(DeleteView):
    model = Seller
    form_class = SellerForm
    # fields = '__all__' <<------ no aplica porque ya esta incluido en el clientform
    # template_name_suffix = '_confirm_delete' <<------por defecto
    success_url = reverse_lazy('sellers:seller_list')
    success_message = "El vendedor ha sido eliminado con exito"
    error_message = "No es posible eliminar al vendedor. Esto puede deberse a que: " \
                    "\n - El cliente tiene ventas asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteSeller, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('sellers:seller_list')

sellers/templates/sellers/seller_confirm_delete.html
{% include 'delete_form.html' %}

sellers/templates/sellers/seller_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nuevo Vendedor{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

sellers/templates/sellers/seller_list.html
{% extends 'base.html' %}

<h2>{% block title %}Vendedores{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Vendedor</th>
                    <th>Nombre Vendedor</th>
                    <th>Telefono</th>
                    <th>Email</th>
                </tr>

                    {% for seller in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'sellers:seller-update' seller.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'sellers:seller-delete' seller.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ seller.seller_code }}</td>
                            <td>{{ seller.seller_name }}</td>
                            <td>{{ seller.seller_tel }}</td>
                            <td>{{ seller.seller_email }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay vendedores registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'sellers:seller-add' %}" class="btn btn-success">Crear Vendedor</a>
    <br>
    <br>

{% endblock %}

sellers/templates/sellers/seller_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Vendedor: {{ object.seller_code }} - {{ object.seller_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}