clients/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from clients.api import views


urlpatterns = [
    # /clients
    url(r'^$', views.ClientListCreateView.as_view(), name='clients'),
    url(r'^(?P<pk>[0-9]+)/$', views.ClientDetailUpdateDeleteView.as_view(), name='clientdetail'),
    url(r'^(?P<pk>[0-9]+)/contacts/$', views.ClientContactListCreateView.as_view(), name='clientcontacts'),
    url(r'^contacts/(?P<pk>[0-9]+)/$', views.ClientContactDetailUpdateDeleteView.as_view(), name='clientcontactdetail'),
    # url(r'^create/$', views.ClientCreateView.as_view(), name='clientcreate')

]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'xml'])

clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'clients'

urlpatterns = [
    # clients
    url(r'^$', views.ClientListView.as_view(), name='client_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.ClientDetailView.as_view(), name='client_detail'),
    url(r'^add/$', views.CreateClient.as_view(), name='client-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateClient.as_view(), name='client-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteClient.as_view(), name='client-delete'),

    # client contacts
    url(r'^(?P<pk>[0-9]+)/contacts/$', views.ClientContactListView.as_view(), name='contact_list'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/$', views.ClientContactDetailView.as_view(), name='contact_detail'),
    url(r'^client_contacts/add/$', views.CreateClientContact.as_view(), name='contact-add'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/update/$', views.UpdateClientContact.as_view(), name='contact-update'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/delete/$', views.DeleteClientContact.as_view(), name='contact-delete'),


]

smartERP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'clients/', include('clients.urls', namespace='clients')),
    url(r'sellers/', include('sellers.urls', namespace='sellers')),
    url(r'management/', include('management.urls', namespace='management')),
    url(r'payment/', include('payment.urls', namespace='payment')),
    url(r'inventory/', include('inventory.urls', namespace='inventory')),
]

clients/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError


def rut_validate(value):
    validador = [2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

    if len(value) == 10 and value.index('-') == 8 and value.count('-') == 1:
        rut = value
    elif len(value) == 9 and value.index('-') == 7 and value.count('-') == 1:
        rut = '0' + value
    else:
        raise ValidationError('Por favor ingrese el rut sin puntos y con guion. Ej. 11111111-1')
    spl_rut = rut.rsplit('-')
    if spl_rut[1] in ('k', 'K'):
        spl_rut.pop()
        spl_rut = spl_rut + ['10']
    elif spl_rut[1] == '0':
        spl_rut.pop()
        spl_rut = spl_rut + ['11']

    rut1 = list(map(int, spl_rut[0]))
    suma = 0
    for i in range(len(spl_rut[0])):
        suma = suma + rut1[-(i+1)]*validador[i]

    if (11 - suma % 11) != int(spl_rut[1]):
        raise ValidationError('El rut que ha ingresado es incorrecto. Por favor intente nuevamente')


# Create your models here.
class Client(models.Model):
    client_rut = models.CharField(max_length=12, unique=True, verbose_name="RUT", validators=[rut_validate])
    client_name = models.CharField(max_length=250, verbose_name="Nombre Cliente")
    client_giro = models.CharField(max_length=200, verbose_name="Giro")
    client_address = models.CharField(max_length=100, verbose_name="Direccion")
    client_comuna = models.CharField(max_length=50, verbose_name="Comuna")
    client_ciudad = models.CharField(max_length=50, verbose_name="Ciudad")
    client_region = models.CharField(max_length=50, verbose_name="Region")
    client_tel = models.CharField(max_length=20, blank=True, verbose_name="Telefono")
    client_email = models.EmailField(blank=True, verbose_name="E-mail")
    is_active = models.BooleanField(default=True, verbose_name="Activo")

    def get_absolute_url(self):
        return reverse('clients:client_list')

    class Meta:
        ordering = ['client_rut']

    def __str__(self):
        return self.client_rut + ' - ' + self.client_name


class ClientContact(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT, verbose_name="Cliente")
    contact_name = models.CharField(max_length=250, verbose_name="Nombre Contacto")
    contact_role = models.CharField(max_length=200, blank=True, verbose_name="Cargo")
    contact_tel = models.CharField(max_length=20, blank=True, verbose_name="Telefono")
    contact_email = models.EmailField(blank=True, verbose_name="E-Mail")

    def get_absolute_url(self):
        return reverse('clients:client_list')

    class Meta:
        ordering = ['contact_name']

    def __str__(self):
        return self.contact_name

clients/forms.py
from django import forms
from .models import Client, ClientContact


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
            'client_rut': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'client_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'client_giro': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'client_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'client_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'client_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'client_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'client_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'client_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }

class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
            'client_rut': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'client_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'client_giro': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'client_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'client_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'client_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'client_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'client_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'client_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }

class ClientContactForm(forms.ModelForm):
    class Meta:
        model = ClientContact
        fields = '__all__'
        widgets = {
            'contact_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'contact_role': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'contact_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'contact_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }

class ClientContactUpdateForm(forms.ModelForm):
    class Meta:
        model = ClientContact
        fields = [
            'contact_name',
            'contact_role',
            'contact_tel',
            'contact_email',
        ]
        widgets = {
            'contact_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'contact_role': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'contact_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'contact_email': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }

clients/api/views.py
from rest_framework import generics, views
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q

from clients.api.serializers import (
    ClientListSerializer,
    ClientDetailSerializer,
    ClientContactListSerializer,
    ClientContactDetailSerializer
)

from clients.models import Client, ClientContact


# list clients/ create new client
class ClientListCreateView(generics.ListCreateAPIView):
    serializer_class = ClientListSerializer
    def get_queryset(self, *args, **kwargs):
        queryset_list = Client.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                    Q(client_rut__icontains=query) |
                    Q(client_name__icontains=query) |
                    Q(client_giro__icontains=query)
                    ).distinct()
        return queryset_list


# display/update/delete client
class ClientDetailUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Client.objects.all()
    serializer_class = ClientDetailSerializer

# list client contacts/ create new client contact
class ClientContactListCreateView(generics.ListCreateAPIView):
    queryset = ClientContact.objects.all()
    serializer_class = ClientContactListSerializer


class ClientContactDetailUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = ClientContact.objects.all()
    serializer_class = ClientContactDetailSerializer

clients/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Client, ClientContact
from .forms import ClientForm, ClientUpdateForm, ClientContactForm, ClientContactUpdateForm
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db.models.deletion import ProtectedError
from django.shortcuts import redirect
from django.utils.html import mark_safe


# ----------clientes------------
class ClientListView(ListView):
    template_name = 'clients/client_list.html'

    def get_queryset(self):
        return Client.objects.all()


class ClientDetailView(DetailView):
    model = Client
    form_class = ClientForm
    template_name = 'clients/client_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ClientDetailView, self).get_context_data(**kwargs)
        context["client"] = Client.objects.get(pk=self.kwargs['pk'])
        return context


class CreateClient(SuccessMessageMixin, CreateView):
    model = Client
    form_class = ClientForm
    # fields = '__all__'  <<------ no aplica porque ya esta incluido en el clientform
    template_name_suffix = '_create_form'
    success_message = "El cliente ha sido creado con exito"


class UpdateClient(UpdateView):
    model = Client
    form_class = ClientUpdateForm
    # fields = '__all__'  <<------ no aplica porque ya esta incluido en el clientform
    template_name_suffix = '_update_form'


class DeleteClient(DeleteView):
    model = Client
    form_class = ClientForm
    # fields = '__all__' <<------ no aplica porque ya esta incluido en el clientform
    # template_name_suffix = '_confirm_delete' <<------por defecto
    success_url = reverse_lazy('clients:client_list')
    success_message = "El cliente ha sido eliminado con exito"
    error_message = "No es posible eliminar al cliente. Esto puede deberse a que: " \
                    "\n - El cliente tiene contactos asociados" \
                    "\n - El cliente tiene cotizaciones asociadas" \
                    "\n - El cliente tiene ventas asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteClient, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('clients:client_list')


# ----------contactos------------
class ClientContactListView(ListView):
    template_name = 'clients/clientcontact_list.html'
    
    def get_queryset(self):
        self.client = get_object_or_404(Client, pk=self.kwargs['pk'])
        return ClientContact.objects.filter(client=self.client)
    
    def get_context_data(self, **kwargs):
        context = super(ClientContactListView, self).get_context_data(**kwargs)
        context["client"] = Client.objects.get(pk=self.kwargs['pk'])
        return context
        


class ClientContactDetailView(DetailView):
    model = ClientContact
    form_class = ClientContactForm
    template_name = 'clients/contact_detail.html'
    def get_context_data(self, **kwargs):
        context = super(ClientContactDetailView, self).get_context_data(**kwargs)
        context["client"] = Client.objects.get(pk=self.kwargs['pk'])
        context["clientcontact"] = ClientContact.objects.get(pk=self.kwargs['pk2'])
        return context


class CreateClientContact(CreateView):
    model = ClientContact
    form_class = ClientContactForm
    # fields = '__all__'
    template_name_suffix = '_create_form'
    success_message = 'El contacto ha sido creado con exito'


class UpdateClientContact(UpdateView):
    model = ClientContact
    form_class = ClientContactUpdateForm
    # fields = '__all__'
    template_name_suffix = '_update_form'


class DeleteClientContact(DeleteView):
    model = ClientContact
    form_class = ClientContactForm
    # fields = '__all__'
    # template_name_suffix = '_confirm_delete' <<------por defecto
    success_url = reverse_lazy('clients:client_list')
    success_message = "El contacto ha sido eliminado con exito"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, mark_safe(self.success_message))
        return super(DeleteClientContact, self).delete(request, *args, **kwargs)

clients/templates/clients/client_confirm_delete.html
{% include 'delete_form.html' %}

clients/templates/clients/client_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nuevo Cliente{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'base.html' %}

<h2>{% block title %}Listado de Clientes{% endblock %}</h2>

{% block body %}

{#    {% if messages %}#}
{#        <div class="row">#}
{#            <div class="col-xs-12">#}
{##}
{#                {% for message in messages %}#}
{#                    <p{% if message.tags == 'success'%} class="alert alert-dismissible alert-success" {% elif message.tags == 'error' %} class="alert alert-dismissible alert-danger" {% endif %}>#}
{#                        <button type="button" class="close" data-dismiss="alert">&times;</button>#}
{#                        <i {% if message.tags == 'success'%} class="fa fa-check" {% elif message.tags == 'error' %} class='fa fa-times' {% endif %} aria-hidden="true">&nbsp;</i>#}
{#                        {{ message|linebreaksbr }}#}
{#                    </p>#}
{#                {% endfor %}#}
{##}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>RUT Cliente</th>
                    <th>Nombre Cliente</th>
                    <th>Comuna</th>
                    <th>Telefono</th>
                    <th>Contactos</th>
                </tr>

                    {% for client in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'clients:client-update' client.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'clients:client-delete' client.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ client.client_rut }}</td>
                            <td>{{ client.client_name }}</td>
                            <td>{{ client.client_comuna }}</td>
                            <td>{{ client.client_tel }}</td>
                            <td>
                                <a href="{% url 'clients:contact_list' client.pk %}" class="btn btn-default btn-sm">Contactos</a>
                            </td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay clientes registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'clients:client-add' %}" class="btn btn-success">Crear Cliente</a>
    <br>
    <br>


{% endblock %}

clients/templates/clients/client_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Cliente: {{ object.client_rut }} - {{ object.client_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

clients/templates/clients/clientcontact_confirm_delete.html
{% include 'delete_form.html' %}

clients/templates/clients/clientcontact_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nuevo Contacto{% endblock %}</h2>

{% block body %}
{%  include 'create_form.html' %}
{% endblock %}

clients/templates/clients/clientcontact_list.html
{% extends 'base.html' %}

<h2>{% block title %}Contactos: {{ client.client_rut }} - {{ client.client_name }}{% endblock %}</h2>

{% block body %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Nombre Cliente</th>
                    <th>Cargo</th>
                    <th>Telefono</th>
                    <th>Email</th>
                </tr>

                    {% for contact in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'clients:contact-update' contact.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'clients:contact-delete' contact.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ contact.contact_name }}</td>
                            <td>{{ contact.contact_role }}</td>{# no es el nombre#}
                            <td>{{ contact.contact_tel }}</td>
                            <td>{{ contact.contact_email }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay contactos registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'clients:contact-add' %}" class="btn btn-success">Crear Contacto</a>
    <br>
    <br>


{% endblock %}

clients/templates/clients/clientcontact_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Contacto: {{ object.contact_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

clients/templates/clients/contact_delete_form.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

clients/templates/clients/contact_detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

clients/templates/clients/contact_list.html
{% extends 'base.html' %}

<h2>{% block title %}Contactos: {{ client.client_rut }} - {{ client.client_name }}{% endblock %}</h2>

{% block body %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Nombre Cliente</th>
                    <th>Cargo</th>
                    <th>Telefono</th>
                    <th>Email</th>
                </tr>

                    {% for contact in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'clients:contact-update' contact.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'clients:contact-delete' contact.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ contact.contact_name }}</td>
                            <td>{{ contact.contact_role }}</td>{# no es el nombre#}
                            <td>{{ contact.contact_tel }}</td>
                            <td>{{ contact.contact_email }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay contactos registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'clients:contact-add' %}" class="btn btn-success">Crear Contacto</a>
    <br>
    <br>


{% endblock %}