clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'clients'

urlpatterns = [
    # clients
    url(r'^$', views.ClientListView.as_view(), name='client_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.ClientDetailView.as_view(), name='client_detail'),
    url(r'^add/$', views.CreateClient.as_view(), name='client-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateClient.as_view(), name='client-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteClient.as_view(), name='client-delete'),

    # client contacts
    url(r'^(?P<pk>[0-9]+)/contacts/$', views.ClientContactListView.as_view(), name='contact_list'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/$', views.ClientContactDetailView.as_view(), name='contact_detail'),
    url(r'^client_contacts/add/$', views.CreateClientContact.as_view(), name='contact-add'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/update/$', views.UpdateClientContact.as_view(), name='contact-update'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/delete/$', views.DeleteClientContact.as_view(), name='contact-delete'),


]

management/urls.py
from django.conf.urls import url
from . import views

app_name = "management"

urlpatterns = [
    #warehouse
    url(r'^warehouse/$', views.WarehouseListView.as_view(), name='warehouse_list'),
    url(r'^warehouse/add/$', views.CreateWarehouse.as_view(), name='warehouse-add'),
    url(r'^warehouse/(?P<pk>[0-9]+)/update/$', views.UpdateWarehouse.as_view(), name='warehouse-update'),
    url(r'^warehouse/(?P<pk>[0-9]+)/delete/$', views.DeleteWarehouse.as_view(), name='warehouse-delete'),

    #branch
    url(r'^branch/$', views.BranchListView.as_view(), name='branch_list'),
    url(r'^branch/add/$', views.CreateBranch.as_view(), name='branch-add'),
    url(r'^branch/(?P<pk>[0-9]+)/update/$', views.UpdateBranch.as_view(), name='branch-update'),
    url(r'^branch/(?P<pk>[0-9]+)/delete/$', views.DeleteBranch.as_view(), name='branch-delete')



]

smartERP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'clients/', include('clients.urls', namespace='clients')),
    url(r'sellers/', include('sellers.urls', namespace='sellers')),
    url(r'management/', include('management.urls', namespace='management')),
    url(r'payment/', include('payment.urls', namespace='payment')),
    url(r'inventory/', include('inventory.urls', namespace='inventory')),
]

management/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Warehouse(models.Model):
    warehouse_code = models.CharField(max_length=10, verbose_name='Codigo Bodega', unique='True')
    warehouse_name = models.CharField(max_length=45, verbose_name='Nombre Bodega')
    warehouse_address = models.CharField(max_length=100, blank=True, verbose_name='Direccion')
    warehouse_comuna = models.CharField(max_length=50, blank=True, verbose_name='Comuna')
    warehouse_ciudad = models.CharField(max_length=50, blank=True, verbose_name='ciudad')
    warehouse_region = models.CharField(max_length=50, blank=True, verbose_name='Region')
    warehouse_tel = models.CharField(max_length=50, blank=True, verbose_name='Telefono')
    is_active = models.BooleanField(default=True, verbose_name='Activo')

    def get_absolute_url(self):
        return reverse('management:warehouse_list')

    def __str__(self):
        return self.warehouse_code + ' - ' + self.warehouse_name

    class Meta:
        ordering = ['warehouse_code']


class Branch(models.Model):
    branch_code = models.CharField(max_length=10, verbose_name='Codigo Sucursal', unique='True')
    branch_name = models.CharField(max_length=45)
    branch_address = models.CharField(max_length=100, blank=True)
    branch_comuna = models.CharField(max_length=50, blank=True)
    branch_ciudad = models.CharField(max_length=50, blank=True)
    branch_region = models.CharField(max_length=50, blank=True)
    branch_tel = models.CharField(max_length=50, blank=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('management:branch_list')

    def __str__(self):
        return self.branch_code + ' - ' + self.branch_name

    class Meta:
        ordering = ['branch_code']

management/forms.py
from django import forms
from .models import Warehouse, Branch


# warehouse
class WarehouseForm(forms.ModelForm):
    class Meta:
        model = Warehouse
        fields = '__all__'
        widgets = {
            'warehouse_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'warehouse_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'warehouse_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'warehouse_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'warehouse_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'warehouse_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'warehouse_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
        }


class WarehouseUpdateForm(forms.ModelForm):
    class Meta:
        model = Warehouse
        fields = '__all__'
        widgets = {
            'warehouse_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'warehouse_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'warehouse_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'warehouse_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'warehouse_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'warehouse_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'warehouse_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
        }


# branch
class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'
        widgets = {
            'branch_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'branch_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'branch_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'branch_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'branch_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'branch_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'branch_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
        }


class BranchUpdateForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'
        widgets = {
            'branch_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'branch_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'branch_address': forms.TextInput(attrs={'class': 'form control', 'size': '70'}),
            'branch_comuna': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'branch_ciudad': forms.TextInput(attrs={'class': 'form control', 'size': '20'}),
            'branch_region': forms.TextInput(attrs={'class': 'form control', 'size': '10'}),
            'branch_tel': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
        }

management/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Warehouse, Branch
from .forms import WarehouseForm, WarehouseUpdateForm, BranchForm, BranchUpdateForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.html import mark_safe
from django.db.models.deletion import ProtectedError


# warehouse
class WarehouseListView(ListView):
    template_name = 'management/warehouse_list.html'

    def get_queryset(self):
        return Warehouse.objects.all()


class CreateWarehouse(SuccessMessageMixin, CreateView):
    model = Warehouse
    form_class = WarehouseForm
    template_name_suffix = '_create_form'
    success_message = "La bodega ha sido creada con exito"


class UpdateWarehouse(UpdateView):
    model = Warehouse
    form_class = WarehouseUpdateForm
    template_name_suffix = '_update_form'


class DeleteWarehouse(DeleteView):
    model = Warehouse
    form_class = WarehouseForm
    success_url = reverse_lazy('management:warehouse_list')
    success_message = "La bodega ha sido eliminada con exito"
    error_message = "No es posible eliminar la bodega. Esto puede deberse a que: " \
                    "\n - La bodega tiene ventas asociadas" \
                    "\n - La bodega tiene compras asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteWarehouse, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('management:warehouse_list')


#branch
class BranchListView(ListView):
    template_name = 'management/branch_list.html'

    def get_queryset(self):
        return Branch.objects.all()


class CreateBranch(SuccessMessageMixin, CreateView):
    model = Branch
    form_class = BranchForm
    template_name_suffix = '_create_form'
    success_message = "La sucursal ha sido creada con exito"


class UpdateBranch(UpdateView):
    model = Branch
    form_class = BranchUpdateForm
    template_name_suffix = '_update_form'


class DeleteBranch(DeleteView):
    model = Branch
    form_class = BranchForm
    success_url = reverse_lazy('management:branch_list')
    success_message = "La sucursal ha sido eliminada con exito"
    error_message = "No es posible eliminar la sucursal. Esto puede deberse a que: " \
                    "\n - La sucursal tiene ventas asociadas" \
                    "\n - La sucursal tiene compras asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteBranch, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('management:branch_list')

management/templates/management/branch_confirm_delete.html
{% include 'delete_form.html' %}

management/templates/management/branch_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nueva Sucursal{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

management/templates/management/branch_list.html
{% extends 'base.html' %}

<h2>{% block title %}Sucursales{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Sucursal</th>
                    <th>Nombre Sucursal</th>
                    <th>Direccion</th>
                    <th>Comuna</th>
                    <th>Telefono</th>
                </tr>

                    {% for branch in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'management:branch-update' branch.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'management:branch-delete' branch.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ branch.branch_code }}</td>
                            <td>{{ branch.branch_name }}</td>
                            <td>{{ branch.branch_address }}</td>
                            <td>{{ branch.branch_comuna }}</td>
                            <td>{{ branch.branch_tel }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay sucursales registradas</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'management:branch-add' %}" class="btn btn-success">Crear sucursal</a>
    <br>
    <br>

{% endblock %}

management/templates/management/branch_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Sucursal: {{ object.branch_code }} - {{ object.branch_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

management/templates/management/warehouse_confirm_delete.html
{% include 'delete_form.html' %}

management/templates/management/warehouse_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nueva Bodega{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

management/templates/management/warehouse_list.html
{% extends 'base.html' %}

<h2>{% block title %}Bodegas{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Bodega</th>
                    <th>Nombre Bodega</th>
                    <th>Direccion</th>
                    <th>Comuna</th>
                    <th>Telefono</th>
                </tr>

                    {% for warehouse in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'management:warehouse-update' warehouse.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'management:warehouse-delete' warehouse.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ warehouse.warehouse_code }}</td>
                            <td>{{ warehouse.warehouse_name }}</td>
                            <td>{{ warehouse.warehouse_address }}</td>
                            <td>{{ warehouse.warehouse_comuna }}</td>
                            <td>{{ warehouse.warehouse_tel }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay bodegas registradas</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'management:warehouse-add' %}" class="btn btn-success">Crear bodega</a>
    <br>
    <br>

{% endblock %}

management/templates/management/warehouse_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Bodega: {{ object.warehouse_code }} - {{ object.warehouse_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}