clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'clients'

urlpatterns = [
    # clients
    url(r'^$', views.ClientListView.as_view(), name='client_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.ClientDetailView.as_view(), name='client_detail'),
    url(r'^add/$', views.CreateClient.as_view(), name='client-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateClient.as_view(), name='client-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteClient.as_view(), name='client-delete'),

    # client contacts
    url(r'^(?P<pk>[0-9]+)/contacts/$', views.ClientContactListView.as_view(), name='contact_list'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/$', views.ClientContactDetailView.as_view(), name='contact_detail'),
    url(r'^client_contacts/add/$', views.CreateClientContact.as_view(), name='contact-add'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/update/$', views.UpdateClientContact.as_view(), name='contact-update'),
    url(r'^client_contacts/(?P<pk>[0-9]+)/delete/$', views.DeleteClientContact.as_view(), name='contact-delete'),


]

payment/urls.py
from django.conf.urls import url
from . import views

app_name = "payment"

urlpatterns = [
    # payment
    url(r'^payform/$', views.PayformListView.as_view(), name='payform_list'),
    url(r'^payform/add/$', views.CreatePayform.as_view(), name='payform-add'),
    url(r'^payform/(?P<pk>[0-9]+)/update/$', views.UpdatePayform.as_view(), name='payform-update'),
    url(r'^payform/(?P<pk>[0-9]+)/delete/$', views.DeletePayform.as_view(), name='payform-delete'),

    # credit condition
    url(r'^credit_cond/$', views.CreditConditionListView.as_view(), name='creditcondition_list'),
    url(r'^credit_cond/add/$', views.CreateCreditCondition.as_view(), name='creditcondition-add'),
    url(r'^credit_cond/(?P<pk>[0-9]+)/update/$', views.UpdateCreditCondition.as_view(), name='creditcondition-update'),
    url(r'^credit_cond/(?P<pk>[0-9]+)/delete/$', views.DeleteCreditCondition.as_view(), name='creditcondition-delete'),

    # inventory movement type
    url(r'^invmov_type/$', views.InventoryMovementTypeListView.as_view(), name='inventorymovementtype_list'),
    url(r'^invmov_type/add/$', views.CreateInventoryMovementType.as_view(), name='inventorymovementtype-add'),
    url(r'^invmov_type/(?P<pk>[0-9]+)/update/$', views.UpdateInventoryMovementType.as_view(), name='inventorymovementtype-update'),
    url(r'^invmov_type/(?P<pk>[0-9]+)/delete/$', views.DeleteInventoryMovementType.as_view(), name='inventorymovementtype-delete'),

    # sale doc type
    url(r'^saledoctype/$', views.SaleDocTypeListView.as_view(), name='saledoctype_list'),
    url(r'^saledoctype/add/$', views.CreateSaleDocType.as_view(), name='saledoctype-add'),
    url(r'^saledoctype/(?P<pk>[0-9]+)/update/$', views.UpdateSaleDocType.as_view(), name='saledoctype-update'),
    url(r'^saledoctype/(?P<pk>[0-9]+)/delete/$', views.DeleteSaleDocType.as_view(), name='saledoctype-delete'),

    # purchase doc type
    # url(r'^purchasedoctype/$', views.PurchaseDocTypeListView.as_view(), name='purchasedoctype_list'),
    # url(r'^purchasedoctype/add/$', views.CreatePurchaseDocType.as_view(), name='purchasedoctype-add'),
    # url(r'^purchasedoctype/(?P<pk>[0-9]+)/update/$', views.UpdatePurchaseDocType.as_view(), name='purchasedoctype-update'),
    # url(r'^purchasedoctype/(?P<pk>[0-9]+)/delete/$', views.DeletePurchaseDocType.as_view(), name='purchasedoctype-delete'),

    # tax
    url(r'^tax/$', views.TaxListView.as_view(), name='tax_list'),
    url(r'^tax/add/$', views.CreateTax.as_view(), name='tax-add'),
    url(r'^tax/(?P<pk>[0-9]+)/update/$', views.UpdateTax.as_view(), name='tax-update'),
    url(r'^tax/(?P<pk>[0-9]+)/delete/$', views.DeleteTax.as_view(), name='tax-delete'),

]

smartERP/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'clients/', include('clients.urls', namespace='clients')),
    url(r'sellers/', include('sellers.urls', namespace='sellers')),
    url(r'management/', include('management.urls', namespace='management')),
    url(r'payment/', include('payment.urls', namespace='payment')),
    url(r'inventory/', include('inventory.urls', namespace='inventory')),
]

payment/forms.py
from django import forms
from .models import Payform, CreditCondition, InventoryMovementType, SaleDocType, PurchaseDocType, Tax


# payform
class PayformForm(forms.ModelForm):
    class Meta:
        model = Payform
        fields = '__all__'
        widgets = {
            'payform_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'payform_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


class PayformUpdateForm(forms.ModelForm):
    class Meta:
        model = Payform
        fields = '__all__'
        widgets = {
            'payform_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'payform_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


# credit condition
class CreditConditionForm(forms.ModelForm):
    class Meta:
        model = CreditCondition
        fields = '__all__'
        widgets = {
            'cond_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'cond_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'cond_days': forms.TextInput(attrs={'class': 'form control', 'size': '4'}),
            'cond_cuotas': forms.TextInput(attrs={'class': 'form control', 'size': '3'}),
        }


class CreditConditionUpdateForm(forms.ModelForm):
    class Meta:
        model = CreditCondition
        fields = '__all__'
        widgets = {
            'cond_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'cond_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'cond_days': forms.TextInput(attrs={'class': 'form control', 'size': '4'}),
            'cond_cuotas': forms.TextInput(attrs={'class': 'form control', 'size': '3'}),
        }


# inventory movement type
class InventoryMovementTypeForm(forms.ModelForm):
    class Meta:
        model = InventoryMovementType
        fields = '__all__'
        widgets = {
            'movement_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'movement_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


class InventoryMovementTypeUpdateForm(forms.ModelForm):
    class Meta:
        model = InventoryMovementType
        fields = '__all__'
        widgets = {
            'movement_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'movement_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


# sale doc type
class SaleDocTypeForm(forms.ModelForm):
    class Meta:
        model = SaleDocType
        fields = '__all__'
        widgets = {
            'sdoc_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'sdoc_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


class SaleDocTypeUpdateForm(forms.ModelForm):
    class Meta:
        model = SaleDocType
        fields = '__all__'
        widgets = {
            'sdoc_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'sdoc_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
        }


# TODO purchase doc type forms
# purchase doc type


# tax
class TaxForm(forms.ModelForm):
    class Meta:
        model = Tax
        fields = '__all__'
        widgets = {
            'tax_code': forms.TextInput(attrs={'class': 'form control', 'size': '15'}),
            'tax_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'tax_value': forms.TextInput(attrs={'class': 'form control', 'size': '4'}),
        }


class TaxUpdateForm(forms.ModelForm):
    class Meta:
        model = Tax
        fields = '__all__'
        widgets = {
            'tax_code': forms.TextInput(attrs={'class': 'form control', 'size': '15', 'readonly': 'True'}),
            'tax_name': forms.TextInput(attrs={'class': 'form control', 'size': '30'}),
            'tax_value': forms.TextInput(attrs={'class': 'form control', 'size': '4'}),
        }

payment/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Payform, CreditCondition, InventoryMovementType, SaleDocType, PurchaseDocType, Tax
from .forms import (PayformForm, PayformUpdateForm, CreditConditionForm, CreditConditionUpdateForm,
                    InventoryMovementTypeForm, InventoryMovementTypeUpdateForm, SaleDocTypeForm, SaleDocTypeUpdateForm,
                    TaxForm, TaxUpdateForm)
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.html import mark_safe
from django.db.models.deletion import ProtectedError


# payform
class PayformListView(ListView):
    template_name = 'payment/payform_list.html'

    def get_queryset(self):
        return Payform.objects.all()


class CreatePayform(SuccessMessageMixin, CreateView):
    model = Payform
    form_class = PayformForm
    template_name_suffix = '_create_form'
    success_message = "La forma de pago ha sido creada con exito"


class UpdatePayform(UpdateView):
    model = Payform
    form_class = PayformUpdateForm
    template_name_suffix = '_update_form'


class DeletePayform(DeleteView):
    model = Payform
    form_class = PayformForm
    success_url = reverse_lazy('payment:payform_list')
    success_message = "La forma de pago ha sido eliminada con exito"
    error_message = "No es posible eliminar la forma de pago. Esto puede deberse a que: " \
                    "\n - La forma de pago tiene ventas asociadas" \
                    "\n - La forma de pago tiene compras asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeletePayform, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('payment:payform_list')


# credit condition
class CreditConditionListView(ListView):
    template_name = 'payment/creditcondition_list.html'

    def get_queryset(self):
        return CreditCondition.objects.all()


class CreateCreditCondition(SuccessMessageMixin, CreateView):
    model = CreditCondition
    form_class = CreditConditionForm
    template_name_suffix = '_create_form'
    success_message = "La condicion de pago ha sido creada con exito"


class UpdateCreditCondition(UpdateView):
    model = CreditCondition
    form_class = CreditConditionUpdateForm
    template_name_suffix = '_update_form'


class DeleteCreditCondition(DeleteView):
    model = CreditCondition
    form_class = CreditConditionForm
    success_url = reverse_lazy('payment:creditcondition_list')
    success_message = "La condicion de pago ha sido eliminada con exito"
    error_message = "No es posible eliminar la condicion de pago. Esto puede deberse a que: " \
                    "\n - La forma de pago tiene ventas asociadas" \
                    "\n - La forma de pago tiene compras asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteCreditCondition, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('payment:creditcondition_list')


# inventory movement type
class InventoryMovementTypeListView(ListView):
    template_name = 'payment/inventorymovementtype_list.html'

    def get_queryset(self):
        return InventoryMovementType.objects.all()


class CreateInventoryMovementType(SuccessMessageMixin, CreateView):
    model = InventoryMovementType
    form_class = InventoryMovementTypeForm
    template_name_suffix = '_create_form'
    success_message = "El tipo de movimiento de inventario ha sido creado con exito"


class UpdateInventoryMovementType(UpdateView):
    model = InventoryMovementType
    form_class = InventoryMovementTypeUpdateForm
    template_name_suffix = '_update_form'


class DeleteInventoryMovementType(DeleteView):
    model = InventoryMovementType
    form_class = InventoryMovementTypeForm
    success_url = reverse_lazy('payment:inventorymovementtype_list')
    success_message = "El tipo de movimiento de inventario ha sido eliminado con exito"
    error_message = "No es posible eliminar el tipo de movimiento de inventario. Esto puede deberse a que: " \
                    "\n - El tipo de movimiento de inventario tiene ventas asociadas" \
                    "\n - El tipo de movimiento de inventario tiene compras asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteInventoryMovementType, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('payment:inventorymovementtype_list')


# sale doc type
class SaleDocTypeListView(ListView):
    template_name = 'payment/saledoctype_list.html'

    def get_queryset(self):
        return SaleDocType.objects.all()


class CreateSaleDocType(SuccessMessageMixin, CreateView):
    model = SaleDocType
    form_class = SaleDocTypeForm
    template_name_suffix = '_create_form'
    success_message = "El tipo de documento de ventas ha sido creado con exito"


class UpdateSaleDocType(UpdateView):
    model = SaleDocType
    form_class = SaleDocTypeUpdateForm
    template_name_suffix = '_update_form'


class DeleteSaleDocType(DeleteView):
    model = SaleDocType
    form_class = SaleDocTypeForm
    success_url = reverse_lazy('payment:saledoctype_list')
    success_message = "El tipo de documento de ventas ha sido eliminado con exito"
    error_message = "No es posible eliminar el tipo de documento de ventas. Esto puede deberse a que: " \
                    "\n - El tipo de documento tiene ventas asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteSaleDocType, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('payment:saledoctype_list')


# purchase doc type


# tax
class TaxListView(ListView):
    template_name = 'payment/tax_list.html'

    def get_queryset(self):
        return Tax.objects.all()


class CreateTax(SuccessMessageMixin, CreateView):
    model = Tax
    form_class = TaxForm
    template_name_suffix = '_create_form'
    success_message = "El tipo impuesto ha sido creado con exito"


class UpdateTax(UpdateView):
    model = Tax
    form_class = TaxUpdateForm
    template_name_suffix = '_update_form'


class DeleteTax(DeleteView):
    model = Tax
    form_class = TaxForm
    success_url = reverse_lazy('payment:tax_list')
    success_message = "El tipo de impuesto ha sido eliminado con exito"
    error_message = "No es posible eliminar el tipo de impuesto. Esto puede deberse a que: " \
                    "\n - El tipo de impuesto tiene ventas asociadas"

    def delete(self, request, *args, **kwargs):
        try:
            a = super(DeleteTax, self).delete(request, *args, **kwargs)
            messages.success(self.request, mark_safe(self.success_message))
            return a

        except ProtectedError:
            messages.error(self.request, self.error_message)
            return redirect('payment:tax_list')

payment/templates/payment/creditcondition_confirm_delete.html
{% include 'delete_form.html' %}

payment/templates/payment/creditcondition_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nueva Condicion de Pago{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

payment/templates/payment/creditcondition_list.html
{% extends 'base.html' %}

<h2>{% block title %}Condiciones de Pago{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Condicion de Pago</th>
                    <th>Nombre Condicion de Pago</th>
                </tr>

                    {% for creditcondition in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'payment:creditcondition-update' creditcondition.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'payment:creditcondition-delete' creditcondition.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ creditcondition.cond_code }}</td>
                            <td>{{ creditcondition.cond_name }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay condiciones de pago registradas</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'payment:creditcondition-add' %}" class="btn btn-success">Crear condicion de pago</a>
    <br>
    <br>

{% endblock %}

payment/templates/payment/creditcondition_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Condicion de Pago: {{ object.cond_code }} - {{ object.cond_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

payment/templates/payment/inventorymovementtype_confirm_delete.html
{% include 'delete_form.html' %}

payment/templates/payment/inventorymovementtype_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nueva Tipo de Movimiento de Inventario{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

payment/templates/payment/inventorymovementtype_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Tipo de Movimiento de Inventario: {{ object.movement_code }} - {{ object.movement_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

payment/templates/payment/payform_confirm_delete.html
{% include 'delete_form.html' %}

payment/templates/payment/payform_create_form.html
{% extends 'base.html' %}

<h2>{% block title %}Nueva Forma de Pago{% endblock %}</h2>

{% block body %}
{% include 'create_form.html' %}
{% endblock %}

payment/templates/payment/saledoctype_confirm_delete.html
{% include 'delete_form.html' %}

payment/templates/payment/saledoctype_list.html
{% extends 'base.html' %}

<h2>{% block title %}Tipos de Documento de Ventas{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Documento de Ventas</th>
                    <th>Nombre Documento de Ventas</th>
                    <th>Codigo SII</th>
                    <th>Tipo de movimiento de inventario</th>
                </tr>

                    {% for saledoctype in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'payment:saledoctype-update' saledoctype.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'payment:saledoctype-delete' saledoctype.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ saledoctype.sdoc_code }}</td>
                            <td>{{ saledoctype.sdoc_name }}</td>
                            <td>{{ saledoctype.ssii_code }}</td>
                            <td>{{ saledoctype.inv_movement_type }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay tipos de movimiento de ventas registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'payment:saledoctype-add' %}" class="btn btn-success">Crear Tipo de Documento de Ventas</a>
    <br>
    <br>

{% endblock %}

payment/templates/payment/saledoctype_update_form.html
{% extends 'base.html' %}

<h2>{% block title %}Editar Tipo de Documento de Ventas: {{ object.sdoc_code }} - {{ object.sdoc_name }}{% endblock %}</h2>

{% block body %}
{% include 'update_form.html' %}
{% endblock %}

payment/templates/payment/tax_confirm_delete.html
{% include 'delete_form.html' %}

payment/templates/payment/tax_list.html
{% extends 'base.html' %}

<h2>{% block title %}Impuestos{% endblock %}</h2>

{% block body %}

    {% include 'form-message.html' %}

    <table>
            {% if object_list %}
                <tr>
                    <th></th>
                    <th>Codigo Impuesto</th>
                    <th>Nombre Impuesto</th>
                    <th>Valor Impuesto</th>
                </tr>

                    {% for tax in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'payment:tax-update' tax.pk %}"><i class="fa fa-pencil-square-o" title="Editar"></i></a>&nbsp;
                                <a href="{% url 'payment:tax-delete' tax.pk %}"><i class="fa fa-times-circle" title="Eliminar"></i></a>
                            </td>
                            <td>{{ tax.tax_code }}</td>
                            <td>{{ tax.tax_name }}</td>
                            <td>{{ tax.tax_value }}</td>
                        </tr>

                    {% endfor %}
            {% else %}
                <h3>No hay impuestos registrados</h3>
            {% endif %}
    </table>
    <br>
    <br>
    <a href="{% url 'payment:tax-add' %}" class="btn btn-success">Crear nuevo impuesto</a>
    <br>
    <br>

{% endblock %}